substitutions:
  name: box01
  friendly_name: Box1

esphome:
  name: $name
  platform: ESP32
  board: nodemcu-32s
  name_add_mac_suffix: false
  project:
    name: jfacevedo80.boxes
    version: "1.2"

wifi:
  networks:
    - ssid: !secret wifi_ssid_iot
      password: !secret wifi_password_iot
    - ssid: !secret wifi_ssid_ajudf
      password: !secret wifi_password_ajudf
  id: wf

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "12345678"

web_server:
  port: 80

logger:

api:
  password: ""

ota:
  password: ""

captive_portal: 

improv_serial:

switch:
  - platform: gpio
    id: Box1Toma
    pin: 26
    name: ${friendly_name} Toma
    inverted: True
    restore_mode: RESTORE_DEFAULT_ON     
  - platform: gpio
    id: PersParar
    pin: 27
    inverted: true
    internal: true
    on_turn_on:
      - delay: 750ms
      - switch.turn_off: PersParar
  - platform: gpio
    id: PersSubir
    pin: 14
    inverted: true
    internal: true
  - platform: gpio
    id: PersBajar
    pin: 13
    inverted: true
    internal: true

output:
  - platform: gpio
    pin: 32
    id: luz_int
    inverted: True
  - platform: gpio
    pin: 33
    id: luz_ext
    inverted: True
    
binary_sensor:
  - platform: gpio
    id: close_endstop
    pin:
      number: 5
      mode: INPUT_PULLUP
    name: ${friendly_name} Contacto
    device_class: door
    filters:
      delayed_off: 2s
  - platform: status
    name: "${friendly_name} Estado"

sensor:
  - platform: dht
    pin: 25
    temperature:
      name: ${friendly_name} Temperatura
      id: sTemp
    humidity:
      name: ${friendly_name} Humedad
      id: sHume
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Tiempo de Actividad"
    entity_category: diagnostic
  
light:
  - platform: binary
    name: ${friendly_name} Luz Interior
    output: luz_int
    id: LuzInt
  - platform: binary
    name: ${friendly_name} Luz Exterior
    output: luz_ext
    id: LuzExt

cover:
  - platform: time_based
    id: blind
    name: "${friendly_name} Persiana"
    open_action:
      - logger.log: "Subiendo persiana..."
      - script.execute: Sube
    open_duration: 48s
    #open_endstop: open_endstop
    close_action:
      - logger.log: "Bajando persiana..."
      - script.execute: Baja
    close_duration: 48s
    #close_endstop: close_endstop
    has_built_in_endstop: true
    stop_action:
      - logger.log: "Deteniendo Persiana..."
      - script.execute: Para
    on_open:
      - logger.log: "Persiana Abierta"
      - switch.turn_off: PersSubir
    on_closed:
      - logger.log: "Persiana Cerrada"
      - switch.turn_off: PersBajar

script:
  - id: Para
    mode: single
    then:
      - if:
          condition:
            - script.is_running: Baja
          then:
            - script.stop: Baja
      - if:
          condition:
            - script.is_running: Sube
          then:
            - script.stop: Sube
      - switch.turn_on: PersParar
      - if:
          condition:
            - switch.is_on: PersBajar
          then:
            - switch.turn_off: PersBajar
      - if:
          condition:
            - switch.is_on: PersSubir
          then:
            - switch.turn_off: PersSubir
  - id: Sube
    mode: single
    then:
      - if:
          condition:
            - script.is_running: Baja
          then:
            - script.stop: Baja
      - switch.turn_on: PersParar
      - delay: 750ms
      - switch.turn_on: PersSubir
  - id: Baja
    mode: single
    then:
      - if:
          condition:
            - script.is_running: Sube
          then:
            - script.stop: Sube
      - switch.turn_on: PersParar
      - delay: 750ms
      - switch.turn_on: PersBajar

button:
  - platform: restart
    id: swrestart
    name: "${friendly_name} Reinicio"
